/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
   
        setIconImage(new ImageIcon(getClass().getResource("../img/logoprogram.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftColumn = new javax.swing.JPanel();
        backGroundBooks = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        buscadorLibroButton = new javax.swing.JLabel();
        clienteButton = new javax.swing.JLabel();
        registroLibroButton = new javax.swing.JLabel();
        prestamosButton = new javax.swing.JLabel();
        cerrarButton = new javax.swing.JLabel();
        minimizarButton = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JLabel();
        instagramIcon = new javax.swing.JLabel();
        facebookIcon = new javax.swing.JLabel();
        twitterIcon = new javax.swing.JLabel();
        ayudaIcon = new javax.swing.JLabel();
        infoIcon = new javax.swing.JLabel();
        panelRedes = new javax.swing.JLabel();
        panelInfoProgram = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftColumn.setBackground(new java.awt.Color(255, 255, 255));
        leftColumn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGroundBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMain650x220.jpg"))); // NOI18N
        leftColumn.add(backGroundBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        getContentPane().add(leftColumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Barbarian", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 106, 163));
        titulo.setText("Lybrarian)");
        menu.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 310, 40));

        buscadorLibroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscador1.jpg"))); // NOI18N
        buscadorLibroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscadorLibroButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscadorLibroButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscadorLibroButtonMouseExited(evt);
            }
        });
        menu.add(buscadorLibroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 230, -1));

        clienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente1.jpg"))); // NOI18N
        clienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clienteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clienteButtonMouseExited(evt);
            }
        });
        menu.add(clienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 230, 200));

        registroLibroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registroLibro1.jpg"))); // NOI18N
        registroLibroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroLibroButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroLibroButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroLibroButtonMouseExited(evt);
            }
        });
        menu.add(registroLibroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        prestamosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamos1.jpg"))); // NOI18N
        prestamosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prestamosButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prestamosButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prestamosButtonMouseExited(evt);
            }
        });
        menu.add(prestamosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.jpg"))); // NOI18N
        cerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseExited(evt);
            }
        });
        menu.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar1.jpg"))); // NOI18N
        minimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseExited(evt);
            }
        });
        menu.add(minimizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion1.jpg"))); // NOI18N
        inicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioSesionMouseExited(evt);
            }
        });
        menu.add(inicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, -1));

        instagramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instagram.png"))); // NOI18N
        menu.add(instagramIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        facebookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook.png"))); // NOI18N
        menu.add(facebookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, -1, -1));

        twitterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gorjeo.png"))); // NOI18N
        menu.add(twitterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        ayudaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion.png"))); // NOI18N
        menu.add(ayudaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        infoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoapp.png"))); // NOI18N
        menu.add(infoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        panelRedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelredes.jpg"))); // NOI18N
        menu.add(panelRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, -1, -1));

        panelInfoProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelinfo.jpg"))); // NOI18N
        menu.add(panelInfoProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //EVENTOS BOTON REGISTROLIBRO
    private void registroLibroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroLibroButtonMouseClicked
        RegistroLibro abrir = new RegistroLibro();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        
    }//GEN-LAST:event_registroLibroButtonMouseClicked

    private void registroLibroButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroLibroButtonMouseEntered
    registroLibroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registroLibro2.jpg"))); // NOI18N
    }//GEN-LAST:event_registroLibroButtonMouseEntered

    private void registroLibroButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroLibroButtonMouseExited
    registroLibroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registroLibro1.jpg"))); // NOI18N
    }//GEN-LAST:event_registroLibroButtonMouseExited

    //EVENTOS BOTON PRESTAMOS
    private void prestamosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosButtonMouseClicked
        Prestamos abrir = new Prestamos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_prestamosButtonMouseClicked

    private void prestamosButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosButtonMouseEntered
    prestamosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamos2.jpg"))); // NOI18N
    }//GEN-LAST:event_prestamosButtonMouseEntered

    private void prestamosButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosButtonMouseExited
    prestamosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamos1.jpg"))); // NOI18N
    }//GEN-LAST:event_prestamosButtonMouseExited

    //EVENTOS BOTON CLIENTE
    private void clienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteButtonMouseClicked
        Cliente abrir = new Cliente();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_clienteButtonMouseClicked

    private void clienteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteButtonMouseEntered
    clienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente2.jpg"))); // NOI18N
    }//GEN-LAST:event_clienteButtonMouseEntered

    private void clienteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteButtonMouseExited
    clienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente1.jpg"))); // NOI18N
    }//GEN-LAST:event_clienteButtonMouseExited

    //EVENTOS BOTON BUSCADOR
    private void buscadorLibroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorLibroButtonMouseClicked
        Buscador abrir = new Buscador();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_buscadorLibroButtonMouseClicked

    private void buscadorLibroButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorLibroButtonMouseEntered
    buscadorLibroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscador2.jpg"))); // NOI18N
    }//GEN-LAST:event_buscadorLibroButtonMouseEntered

    private void buscadorLibroButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorLibroButtonMouseExited
    buscadorLibroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscador1.jpg"))); // NOI18N
    }//GEN-LAST:event_buscadorLibroButtonMouseExited

    //EVENTOS INICIO SESION
    private void inicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseClicked
        InicioSesion abrir = new InicioSesion();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_inicioSesionMouseClicked

    private void inicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseEntered
        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion2.jpg"))); // NOI18N
    }//GEN-LAST:event_inicioSesionMouseEntered

    private void inicioSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseExited
        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion1.jpg"))); // NOI18N
    }//GEN-LAST:event_inicioSesionMouseExited

    //EVENTOS BOTON MINIMIZAR
    private void minimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_minimizarButtonMouseClicked

    private void minimizarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseEntered
        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar2.jpg"))); // NOI18N
    }//GEN-LAST:event_minimizarButtonMouseEntered

    private void minimizarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseExited
        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar1.jpg"))); // NOI18N
    }//GEN-LAST:event_minimizarButtonMouseExited

    //EVENTOS BOTON CERRAR
    private void cerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarButtonMouseClicked

    private void cerrarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseEntered
        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar2.jpg"))); // NOI18N
    }//GEN-LAST:event_cerrarButtonMouseEntered

    private void cerrarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseExited
        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.jpg"))); // NOI18N
    }//GEN-LAST:event_cerrarButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayudaIcon;
    private javax.swing.JLabel backGroundBooks;
    private javax.swing.JLabel buscadorLibroButton;
    private javax.swing.JLabel cerrarButton;
    private javax.swing.JLabel clienteButton;
    private javax.swing.JLabel facebookIcon;
    private javax.swing.JLabel infoIcon;
    private javax.swing.JLabel inicioSesion;
    private javax.swing.JLabel instagramIcon;
    private javax.swing.JPanel leftColumn;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel minimizarButton;
    private javax.swing.JLabel panelInfoProgram;
    private javax.swing.JLabel panelRedes;
    private javax.swing.JLabel prestamosButton;
    private javax.swing.JLabel registroLibroButton;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel twitterIcon;
    // End of variables declaration//GEN-END:variables
}
