/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class Prestamos extends javax.swing.JFrame {

    /**
     * Creates new form Prestamo
     */
    public Prestamos() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../img/logoprogram.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftColumn = new javax.swing.JPanel();
        backGroundBooks1 = new javax.swing.JLabel();
        prestamosMenu = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cerrarButton = new javax.swing.JLabel();
        minimizarButton = new javax.swing.JLabel();
        atrasButton = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JLabel();
        instagramIcon = new javax.swing.JLabel();
        facebookIcon = new javax.swing.JLabel();
        twitterIcon = new javax.swing.JLabel();
        ayudaIcon = new javax.swing.JLabel();
        infoIcon = new javax.swing.JLabel();
        panelRedes = new javax.swing.JLabel();
        panelInfoProgram = new javax.swing.JLabel();
        nombreTituloText = new javax.swing.JLabel();
        nombreTituloTextField = new javax.swing.JTextField();
        cantidadText1 = new javax.swing.JLabel();
        cantidadTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreTituloText1 = new javax.swing.JLabel();
        autorText = new javax.swing.JLabel();
        nombreTituloTextField1 = new javax.swing.JTextField();
        nombreTituloTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonPrestar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftColumn.setBackground(new java.awt.Color(255, 255, 255));
        leftColumn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGroundBooks1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMain650x220.jpg"))); // NOI18N
        leftColumn.add(backGroundBooks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        getContentPane().add(leftColumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        prestamosMenu.setBackground(new java.awt.Color(255, 255, 255));
        prestamosMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Barbarian", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 106, 163));
        titulo.setText("Lybrarian)");
        prestamosMenu.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 310, 40));

        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.jpg"))); // NOI18N
        cerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseExited(evt);
            }
        });
        prestamosMenu.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar1.jpg"))); // NOI18N
        minimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseExited(evt);
            }
        });
        prestamosMenu.add(minimizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retroceder1.jpg"))); // NOI18N
        atrasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasButtonMouseExited(evt);
            }
        });
        prestamosMenu.add(atrasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion1.jpg"))); // NOI18N
        inicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioSesionMouseExited(evt);
            }
        });
        prestamosMenu.add(inicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, -1));

        instagramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instagram.png"))); // NOI18N
        prestamosMenu.add(instagramIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        facebookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook.png"))); // NOI18N
        prestamosMenu.add(facebookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, -1, -1));

        twitterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gorjeo.png"))); // NOI18N
        prestamosMenu.add(twitterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        ayudaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion.png"))); // NOI18N
        prestamosMenu.add(ayudaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        infoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoapp.png"))); // NOI18N
        prestamosMenu.add(infoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        panelRedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelredes.jpg"))); // NOI18N
        prestamosMenu.add(panelRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, -1, -1));

        panelInfoProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelinfo.jpg"))); // NOI18N
        prestamosMenu.add(panelInfoProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        nombreTituloText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        nombreTituloText.setForeground(new java.awt.Color(0, 106, 163));
        nombreTituloText.setText("Nombre del Título:");
        prestamosMenu.add(nombreTituloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        nombreTituloTextField.setBackground(new java.awt.Color(255, 255, 255));
        nombreTituloTextField.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        nombreTituloTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreTituloTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreTituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTituloTextFieldActionPerformed(evt);
            }
        });
        prestamosMenu.add(nombreTituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 270, 30));

        cantidadText1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        cantidadText1.setForeground(new java.awt.Color(0, 106, 163));
        cantidadText1.setText("Cantidad:");
        prestamosMenu.add(cantidadText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        cantidadTextField.setBackground(new java.awt.Color(255, 255, 255));
        cantidadTextField.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        cantidadTextField.setForeground(new java.awt.Color(102, 102, 102));
        cantidadTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cantidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTextFieldActionPerformed(evt);
            }
        });
        prestamosMenu.add(cantidadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.jpg"))); // NOI18N
        prestamosMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        nombreTituloText1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        nombreTituloText1.setForeground(new java.awt.Color(0, 106, 163));
        nombreTituloText1.setText("Nombre del Cliente:");
        prestamosMenu.add(nombreTituloText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        autorText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        autorText.setForeground(new java.awt.Color(0, 106, 163));
        autorText.setText("Apellidos del Cliente:");
        prestamosMenu.add(autorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        nombreTituloTextField1.setBackground(new java.awt.Color(255, 255, 255));
        nombreTituloTextField1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        nombreTituloTextField1.setForeground(new java.awt.Color(102, 102, 102));
        nombreTituloTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreTituloTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTituloTextField1ActionPerformed(evt);
            }
        });
        prestamosMenu.add(nombreTituloTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 270, 30));

        nombreTituloTextField2.setBackground(new java.awt.Color(255, 255, 255));
        nombreTituloTextField2.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        nombreTituloTextField2.setForeground(new java.awt.Color(102, 102, 102));
        nombreTituloTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreTituloTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTituloTextField2ActionPerformed(evt);
            }
        });
        prestamosMenu.add(nombreTituloTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.jpg"))); // NOI18N
        prestamosMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        botonPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestarboton1.jpg"))); // NOI18N
        botonPrestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPrestarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPrestarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPrestarMouseExited(evt);
            }
        });
        prestamosMenu.add(botonPrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechaDerecha.png"))); // NOI18N
        prestamosMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        getContentPane().add(prestamosMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //EVENTOS BOTON CERRAR
    private void cerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarButtonMouseClicked

    private void cerrarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseEntered
        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar2.jpg"))); // NOI18N
    }//GEN-LAST:event_cerrarButtonMouseEntered

    private void cerrarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseExited
        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.jpg"))); // NOI18N
    }//GEN-LAST:event_cerrarButtonMouseExited

    //EVENTOS BOTON MINIMIZAR
    private void minimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_minimizarButtonMouseClicked

    private void minimizarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseEntered
        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar2.jpg"))); // NOI18N
    }//GEN-LAST:event_minimizarButtonMouseEntered

    private void minimizarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseExited
        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar1.jpg"))); // NOI18N
    }//GEN-LAST:event_minimizarButtonMouseExited

    //EVENTOS BOTON ATRAS
    private void atrasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasButtonMouseClicked
        MainPage abrir = new MainPage();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_atrasButtonMouseClicked

    private void atrasButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasButtonMouseEntered
        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retroceder2.jpg"))); // NOI18N
    }//GEN-LAST:event_atrasButtonMouseEntered

    private void atrasButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasButtonMouseExited
        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retroceder1.jpg"))); // NOI18N
    }//GEN-LAST:event_atrasButtonMouseExited

    //EVENTOS BOTON INICIO SESION
    private void inicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseClicked
        InicioSesion abrir = new InicioSesion();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);                                             
    }//GEN-LAST:event_inicioSesionMouseClicked

    private void inicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseEntered
        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion2.jpg"))); // NOI18N
    }//GEN-LAST:event_inicioSesionMouseEntered

    private void inicioSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseExited
        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion1.jpg"))); // NOI18N
    }//GEN-LAST:event_inicioSesionMouseExited

    private void nombreTituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTituloTextFieldActionPerformed

    private void cantidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTextFieldActionPerformed

    private void nombreTituloTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTituloTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTituloTextField1ActionPerformed

    private void nombreTituloTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTituloTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTituloTextField2ActionPerformed

    //EVENTOS BOTON PRESTAR
    private void botonPrestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrestarMouseClicked
        
    }//GEN-LAST:event_botonPrestarMouseClicked

    private void botonPrestarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrestarMouseEntered
        botonPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestarboton2.jpg"))); // NOI18N
    }//GEN-LAST:event_botonPrestarMouseEntered

    private void botonPrestarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrestarMouseExited
        botonPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestarboton1.jpg"))); // NOI18N
    }//GEN-LAST:event_botonPrestarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atrasButton;
    private javax.swing.JLabel autorText;
    private javax.swing.JLabel ayudaIcon;
    private javax.swing.JLabel backGroundBooks1;
    private javax.swing.JLabel botonPrestar;
    private javax.swing.JLabel cantidadText1;
    private javax.swing.JTextField cantidadTextField;
    private javax.swing.JLabel cerrarButton;
    private javax.swing.JLabel facebookIcon;
    private javax.swing.JLabel infoIcon;
    private javax.swing.JLabel inicioSesion;
    private javax.swing.JLabel instagramIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel leftColumn;
    private javax.swing.JLabel minimizarButton;
    private javax.swing.JLabel nombreTituloText;
    private javax.swing.JLabel nombreTituloText1;
    private javax.swing.JTextField nombreTituloTextField;
    private javax.swing.JTextField nombreTituloTextField1;
    private javax.swing.JTextField nombreTituloTextField2;
    private javax.swing.JLabel panelInfoProgram;
    private javax.swing.JLabel panelRedes;
    private javax.swing.JPanel prestamosMenu;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel twitterIcon;
    // End of variables declaration//GEN-END:variables
}
