/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class RegistroLibro extends javax.swing.JFrame {

    /**
     * Creates new form RegistroLibro
     */
    public RegistroLibro() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../img/logoprogram.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftColumn = new javax.swing.JPanel();
        backGroundBooks1 = new javax.swing.JLabel();
        registroLibroMenu = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cerrarButton = new javax.swing.JLabel();
        minimizarButton = new javax.swing.JLabel();
        atrasButton = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JLabel();
        instagramIcon = new javax.swing.JLabel();
        facebookIcon = new javax.swing.JLabel();
        twitterIcon = new javax.swing.JLabel();
        ayudaIcon = new javax.swing.JLabel();
        infoIcon = new javax.swing.JLabel();
        panelRedes = new javax.swing.JLabel();
        panelInfoProgram = new javax.swing.JLabel();
        nombreTituloText = new javax.swing.JLabel();
        nombreTituloTextField = new javax.swing.JTextField();
        autorText = new javax.swing.JLabel();
        autorTextField = new javax.swing.JTextField();
        anoPublicacionText = new javax.swing.JLabel();
        anoPublicacionTextField = new javax.swing.JTextField();
        cantidadText = new javax.swing.JLabel();
        cantidadTextField = new javax.swing.JTextField();
        sinopsisText = new javax.swing.JLabel();
        sinopsisTextArea = new javax.swing.JTextArea();
        grabarTituloButton = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JLabel();
        agregarPortadaButton = new javax.swing.JLabel();
        isbnText1 = new javax.swing.JLabel();
        isbnTextField1 = new javax.swing.JTextField();
        cantidadText1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftColumn.setBackground(new java.awt.Color(255, 255, 255));
        leftColumn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backGroundBooks1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMain650x220.jpg"))); // NOI18N
        leftColumn.add(backGroundBooks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        getContentPane().add(leftColumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        registroLibroMenu.setBackground(new java.awt.Color(255, 255, 255));
        registroLibroMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Barbarian", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 106, 163));
        titulo.setText("Lybrarian)");
        registroLibroMenu.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 310, 40));

        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.jpg"))); // NOI18N
        cerrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarButtonMouseExited(evt);
            }
        });
        registroLibroMenu.add(cerrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar1.jpg"))); // NOI18N
        minimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarButtonMouseExited(evt);
            }
        });
        registroLibroMenu.add(minimizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retroceder1.jpg"))); // NOI18N
        atrasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasButtonMouseExited(evt);
            }
        });
        registroLibroMenu.add(atrasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion1.jpg"))); // NOI18N
        inicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicioSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicioSesionMouseExited(evt);
            }
        });
        registroLibroMenu.add(inicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, -1));

        instagramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instagram.png"))); // NOI18N
        registroLibroMenu.add(instagramIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        facebookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook.png"))); // NOI18N
        registroLibroMenu.add(facebookIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, -1, -1));

        twitterIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gorjeo.png"))); // NOI18N
        registroLibroMenu.add(twitterIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        ayudaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informacion.png"))); // NOI18N
        registroLibroMenu.add(ayudaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        infoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/infoapp.png"))); // NOI18N
        registroLibroMenu.add(infoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        panelRedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelredes.jpg"))); // NOI18N
        registroLibroMenu.add(panelRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, -1, -1));

        panelInfoProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelinfo.jpg"))); // NOI18N
        registroLibroMenu.add(panelInfoProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        nombreTituloText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        nombreTituloText.setForeground(new java.awt.Color(0, 106, 163));
        nombreTituloText.setText("Nombre del Título:");
        registroLibroMenu.add(nombreTituloText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        nombreTituloTextField.setBackground(new java.awt.Color(255, 255, 255));
        nombreTituloTextField.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        nombreTituloTextField.setForeground(new java.awt.Color(102, 102, 102));
        nombreTituloTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nombreTituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTituloTextFieldActionPerformed(evt);
            }
        });
        registroLibroMenu.add(nombreTituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 300, 30));

        autorText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        autorText.setForeground(new java.awt.Color(0, 106, 163));
        autorText.setText("Autor:");
        registroLibroMenu.add(autorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        autorTextField.setBackground(new java.awt.Color(255, 255, 255));
        autorTextField.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        autorTextField.setForeground(new java.awt.Color(102, 102, 102));
        autorTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        autorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorTextFieldActionPerformed(evt);
            }
        });
        registroLibroMenu.add(autorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 300, 30));

        anoPublicacionText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        anoPublicacionText.setForeground(new java.awt.Color(0, 106, 163));
        anoPublicacionText.setText("Año:");
        registroLibroMenu.add(anoPublicacionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        anoPublicacionTextField.setBackground(new java.awt.Color(255, 255, 255));
        anoPublicacionTextField.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        anoPublicacionTextField.setForeground(new java.awt.Color(102, 102, 102));
        anoPublicacionTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        anoPublicacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoPublicacionTextFieldActionPerformed(evt);
            }
        });
        registroLibroMenu.add(anoPublicacionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 140, 30));

        cantidadText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        cantidadText.setForeground(new java.awt.Color(0, 106, 163));
        cantidadText.setText("Género:");
        registroLibroMenu.add(cantidadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        cantidadTextField.setBackground(new java.awt.Color(255, 255, 255));
        cantidadTextField.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        cantidadTextField.setForeground(new java.awt.Color(102, 102, 102));
        cantidadTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cantidadTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTextFieldActionPerformed(evt);
            }
        });
        registroLibroMenu.add(cantidadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 140, 30));

        sinopsisText.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        sinopsisText.setForeground(new java.awt.Color(0, 106, 163));
        sinopsisText.setText("Sinopsis del Libro:");
        registroLibroMenu.add(sinopsisText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        sinopsisTextArea.setBackground(new java.awt.Color(255, 255, 255));
        sinopsisTextArea.setColumns(20);
        sinopsisTextArea.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        sinopsisTextArea.setForeground(new java.awt.Color(102, 102, 102));
        sinopsisTextArea.setLineWrap(true);
        sinopsisTextArea.setRows(5);
        sinopsisTextArea.setAutoscrolls(false);
        sinopsisTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registroLibroMenu.add(sinopsisTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 540, 160));

        grabarTituloButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grabartitulo1.jpg"))); // NOI18N
        grabarTituloButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grabarTituloButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grabarTituloButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grabarTituloButtonMouseExited(evt);
            }
        });
        registroLibroMenu.add(grabarTituloButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar1.jpg"))); // NOI18N
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseExited(evt);
            }
        });
        registroLibroMenu.add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        agregarPortadaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarportada1.jpg"))); // NOI18N
        agregarPortadaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarPortadaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarPortadaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarPortadaButtonMouseExited(evt);
            }
        });
        registroLibroMenu.add(agregarPortadaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        isbnText1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        isbnText1.setForeground(new java.awt.Color(0, 106, 163));
        isbnText1.setText("ISBN:");
        registroLibroMenu.add(isbnText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        isbnTextField1.setBackground(new java.awt.Color(255, 255, 255));
        isbnTextField1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        isbnTextField1.setForeground(new java.awt.Color(102, 102, 102));
        isbnTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        isbnTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextField1ActionPerformed(evt);
            }
        });
        registroLibroMenu.add(isbnTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, 30));

        cantidadText1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd Md", 0, 24)); // NOI18N
        cantidadText1.setForeground(new java.awt.Color(0, 106, 163));
        cantidadText1.setText("Cantidad:");
        registroLibroMenu.add(cantidadText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("TT Rounds Neue Trl Cnd", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aventura", "Acción", "Ciencia Ficción", "Terror", "Misterio", "Autoayuda", "Manuales", "Poesía", "Romántica", "Novela", "Thriller" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registroLibroMenu.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 140, 30));

        getContentPane().add(registroLibroMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTituloTextFieldActionPerformed

    private void autorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorTextFieldActionPerformed

    private void anoPublicacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoPublicacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoPublicacionTextFieldActionPerformed

    private void cantidadTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTextFieldActionPerformed

    //EVENTOS BOTON ATRAS
    private void atrasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasButtonMouseClicked
        MainPage abrir = new MainPage();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);      
    }//GEN-LAST:event_atrasButtonMouseClicked

    private void atrasButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasButtonMouseEntered
        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retroceder2.jpg"))); // NOI18N
    }//GEN-LAST:event_atrasButtonMouseEntered

    private void atrasButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasButtonMouseExited
        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retroceder1.jpg"))); // NOI18N
    }//GEN-LAST:event_atrasButtonMouseExited

    //EVENTOS BOTON MINIMIZAR
    private void minimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_minimizarButtonMouseClicked

    private void minimizarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseEntered
        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar2.jpg"))); // NOI18N
    }//GEN-LAST:event_minimizarButtonMouseEntered

    private void minimizarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarButtonMouseExited
        minimizarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar1.jpg"))); // NOI18N
    }//GEN-LAST:event_minimizarButtonMouseExited

    //EVENTOS BOTON CERRAR
    private void cerrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarButtonMouseClicked

    private void cerrarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseEntered
        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar2.jpg"))); // NOI18N
    }//GEN-LAST:event_cerrarButtonMouseEntered

    private void cerrarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarButtonMouseExited
        cerrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar1.jpg"))); // NOI18N
    }//GEN-LAST:event_cerrarButtonMouseExited

    //EVENTOS BOTON GRABAR TITULO
    private void grabarTituloButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTituloButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grabarTituloButtonMouseClicked

    private void grabarTituloButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTituloButtonMouseEntered
        grabarTituloButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grabartitulo2.jpg"))); // NOI18N
    }//GEN-LAST:event_grabarTituloButtonMouseEntered

    private void grabarTituloButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTituloButtonMouseExited
        grabarTituloButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grabartitulo1.jpg"))); // NOI18N
    }//GEN-LAST:event_grabarTituloButtonMouseExited

    //EVENTOS BOTON CANCELAR
    private void cancelarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseClicked
        MainPage abrir = new MainPage();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarButtonMouseClicked

    private void cancelarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseEntered
        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar2.jpg"))); // NOI18N
    }//GEN-LAST:event_cancelarButtonMouseEntered

    private void cancelarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseExited
        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar1.jpg"))); // NOI18N
    }//GEN-LAST:event_cancelarButtonMouseExited

    //EVENTOS AGREGAR PORTADA 
    private void agregarPortadaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPortadaButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarPortadaButtonMouseClicked

    private void agregarPortadaButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPortadaButtonMouseEntered
        agregarPortadaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarportada2.jpg"))); // NOI18N
    }//GEN-LAST:event_agregarPortadaButtonMouseEntered

    private void agregarPortadaButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarPortadaButtonMouseExited
        agregarPortadaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarportada1.jpg"))); // NOI18N
    }//GEN-LAST:event_agregarPortadaButtonMouseExited

    //EVENTOS INICIO SESION
    private void inicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseClicked
        InicioSesion abrir = new InicioSesion();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     
    }//GEN-LAST:event_inicioSesionMouseClicked

    private void inicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseEntered
        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion2.jpg"))); // NOI18N
    }//GEN-LAST:event_inicioSesionMouseEntered

    private void inicioSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioSesionMouseExited
        inicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iniciarsesion1.jpg"))); // NOI18N
    }//GEN-LAST:event_inicioSesionMouseExited

    private void isbnTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarPortadaButton;
    private javax.swing.JLabel anoPublicacionText;
    private javax.swing.JTextField anoPublicacionTextField;
    private javax.swing.JLabel atrasButton;
    private javax.swing.JLabel autorText;
    private javax.swing.JTextField autorTextField;
    private javax.swing.JLabel ayudaIcon;
    private javax.swing.JLabel backGroundBooks1;
    private javax.swing.JLabel cancelarButton;
    private javax.swing.JLabel cantidadText;
    private javax.swing.JLabel cantidadText1;
    private javax.swing.JTextField cantidadTextField;
    private javax.swing.JLabel cerrarButton;
    private javax.swing.JLabel facebookIcon;
    private javax.swing.JLabel grabarTituloButton;
    private javax.swing.JLabel infoIcon;
    private javax.swing.JLabel inicioSesion;
    private javax.swing.JLabel instagramIcon;
    private javax.swing.JLabel isbnText1;
    private javax.swing.JTextField isbnTextField1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel leftColumn;
    private javax.swing.JLabel minimizarButton;
    private javax.swing.JLabel nombreTituloText;
    private javax.swing.JTextField nombreTituloTextField;
    private javax.swing.JLabel panelInfoProgram;
    private javax.swing.JLabel panelRedes;
    private javax.swing.JPanel registroLibroMenu;
    private javax.swing.JLabel sinopsisText;
    private javax.swing.JTextArea sinopsisTextArea;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel twitterIcon;
    // End of variables declaration//GEN-END:variables
}
